version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/postgres?schema=public"
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    volumes:
      - .:/app
    working_dir: /app
